# Get the box up and running. These tasks run before the box is configured
# or the project is cloned or built. All system dependencies should be
# installed here.

# NOTE: commented out because we do not currently need node on the vm
# - name: add keys to apt
#   apt_key: url={{ item }} state=present
#   with_items: apt.keys

- name: add ppas to apt
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items: '{{apt.ppas}}'

- name: install apt packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items: '{{apt.packages}}'

- name: Check for auto-removable packages
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False

- name: Autoremove unused packages
  command: apt-get -y autoremove
  when: '"packages will be REMOVED" in check_autoremove.stdout'
