# Empty database and delete uploaded files

- debug: msg="wp_empty_db flag is set -- deleting all content!"
  when: wp_empty_db == true

- name: empty the wp database to prepare for fresh content
  command: wp site empty --yes --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root
  when: wp_empty_db == true

- name: remove all uploaded files to prepare for fresh content
  command: rm -rf {{ site.wp_path }}/content/uploads/*
  ignore_errors: true
  when: wp_empty_db == true

# Install WP importer plugin

- name: check whether the wp importer plugin is installed
  command: wp plugin is-installed wordpress-importer --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root
  ignore_errors: true
  register: wp_importer_installed

- debug: msg="importer plugin not present, it will now be installed"
  when: wp_importer_installed|failed

- name: install wp importer plugin
  command: wp plugin install wordpress-importer --path={{ site.wp_path }} --activate
    --allow-root # wp-cli complains when run as root
  when: wp_importer_installed|failed

- name: ensure wp importer plugin is up to date
  command: wp plugin update wordpress-importer --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root

- name: ensure wp importer plugin is active
  command: wp plugin activate wordpress-importer --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root

# Download and install theme unit test data

- name: check whether theme unit test data is already present
  # Antidisestablishmentarianism is a string used in the sample content: its
  # presence is a reasonable indication that we're using the theme test data
  shell: wp post list --path={{ site.wp_path }} --allow-root | grep Antidisestablishmentarianism
  ignore_errors: true
  register: wp_theme_test_data_installed

- name: retrieve the wp.com "theme unit test" sample data
  copy: src=theme-unit-test-data.xml dest=/tmp/theme-unit-test-data.xml
  when: wp_theme_test_data_installed|failed
  register: wp_theme_test_data_retrieved

- name: install "theme unit test" data into wp site
  command: wp import /tmp/theme-unit-test-data.xml --path={{ site.wp_path }} --authors=create
    --allow-root # wp-cli complains when run as root
  when: wp_theme_test_data_retrieved
