#################################################
# Download & Install WP-CLI (http://wp-cli.org/)
#################################################

- name: check whether wp-cli is available
  stat: path=/usr/local/bin/wp
  register: wp_cli

- name: download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp
  when: wp_cli.stat.exists == false

- name: update wp-cli perms to add executable bit
  file: path=/usr/local/bin/wp mode="0755"

###############################
# Download & Install WordPress
###############################

- name: ensure site directory exists
  file: path={{ site.public_path }} state=directory mode=0755 owner='www-data' group='www-data'

# To support switching between nightly builds & stable, always remove & recreate WP core files
#
- name: remove site directory if already present
  file: path={{ site.wp_path }} state=absent

# Download WordPress (Nightly Build) core files

- name: download latest nightly build of wp core
  command: wp core download --path={{ site.wp_path }}
    --version=nightly
    --allow-root
  when: wp_nightly

# Download WordPress (Stable) core files

- name: download latest stable build of wp core
  command: wp core download --path={{ site.wp_path }}
    --allow-root
  when: not wp_nightly

# Create the wp-config.php file

- name: check whether wp-config.php file already exists
  stat: path={{ site.public_path }}/wp-config.php
  register: wp_config

# Note: get_url cannot be used here because its registered output does not include
# the retrieved file's contents. Using curl/stdout feels sub-optimal, but I know
# no other way to read the contents of a remote get into a variable that can then
# be used within a template.
- name: generate the salts to be injected into the generated wp-config.php file
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  when: wp_config.stat.exists == false
  register: wp_salts

- name: generate wp-config.php file from template
  template: src=wp-config.php dest={{ site.public_path }}/wp-config.php owner='www-data' group='www-data' mode='0660'
  when: wp_config.stat.exists == false

# Create the web root-level index.php file

- name: check whether index.php file already exists
  stat: path={{ site.public_path }}/index.php
  register: wp_index_file

- name: copy index.php file from wordpress core directory
  command: cp {{ site.wp_path }}/index.php {{ site.public_path }}/index.php
  become: true
  become_user: www-data # www-data should own the index.php file
  when: wp_index_file.stat.exists == false

- name: update require path in root index.php to point at wp core index.php
  replace: dest={{ site.public_path }}/index.php regexp="'/wp-blog-header.php" replace="'/wp/wp-blog-header.php"
  when: wp_index_file.stat.exists == false

# Install WordPress

- name: check whether wp is already installed
  command: wp core is-installed --path={{ site.wp_path }}
    --allow-root
  ignore_errors: true
  register: wp_installed

- name: install wp
  command: wp core install --path={{ site.wp_path }} --url=http://{{ site.fqdn }} --title='{{ site.title }}' --admin_user='{{ wp.admin.user }}' --admin_password='{{ wp.admin.pass }}' --admin_email='{{ wp.admin.email }}'
    --allow-root # wp-cli complains when run as root
  when: wp_installed|failed

# Install WP-API plugin

- name: check whether the REST API plugin is currently using git
  stat: path={{ site.public_path }}/content/plugins/rest-api/.git
  register: wp_rest_git_dir

- name: remove plugin directory entirely if switching from develop to stable or vice-versa
  file: path={{ site.public_path }}/content/plugins/rest-api state=absent
  when: ((wp_rest_git_dir.stat.exists == true and not wpapi_develop) or (wp_rest_git_dir.stat.exists == false and wpapi_develop))

# DEVELOP: use latest code from git repository

- name: clone and/or update WP REST API plugin into plugins directory
  git: repo=https://github.com/WP-API/WP-API.git dest={{ site.public_path }}/content/plugins/rest-api
  when: wpapi_develop

- name: activate rest-api plugin
  command: wp plugin activate rest-api --path={{ site.wp_path }}
    --allow-root
  when: wpapi_develop

# NON-DEVELOP: use latest stable release from repo

- name: check whether rest-api plugin is already installed
  command: wp plugin is-installed rest-api --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root
  ignore_errors: true
  register: wp_rest_api
  when: not wpapi_develop

- name: install rest-api plugin
  command: wp plugin install rest-api --path={{ site.wp_path }} --activate
    --allow-root # wp-cli complains when run as root
  when: (not wpapi_develop and wp_rest_api|failed)

- name: ensure rest-api plugin is up to date
  command: wp plugin update rest-api --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root
  when: (not wpapi_develop and wp_rest_api|success)

- name: ensure rest-api plugin is active
  command: wp plugin activate rest-api --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root

- name: configure permalinks to enable rest-api plugin to work
  command: wp rewrite structure '/%year%/%monthnum%/%postname%' --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root

# Install WP-API OAuth 1.0a plugin

- name: clone and/or update oauth client plugin into plugins directory
  git: repo=https://github.com/WP-API/OAuth1.git dest={{ site.public_path }}/content/plugins/api-oauth

- name: ensure oauth plugin is activated
  command: wp plugin activate api-oauth --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root

# Install WP-API Basic Auth plugin

- name: clone and/or update basic auth plugin into plugins directory
  git: repo=https://github.com/WP-API/Basic-Auth.git dest={{ site.public_path }}/content/plugins/api-basic-auth

- name: ensure basic auth plugin is activated
  command: wp plugin activate api-basic-auth --path={{ site.wp_path }}
    --allow-root # wp-cli complains when run as root

# Environment cleanup & normalization

- name: Ensure proper WordPress file ownership & permissions (755/644)
  file:
    path: "{{ site.wp_path }}"
    mode: u=rwX,g=rX,o=rX
    owner: www-data
    group: www-data
    recurse: yes
