- hosts: all
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted
  sudo: true
  roles:
      # Install dependencies and get box up to date.
    - base
      # Configure server with users, long-running processes, etc.
    - configure
    - nginx
    - mysql
    - php
      # Set up WP-CLI and use it to install WordPress.
    - wordpress
