- hosts: all
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted
  sudo: true
  roles:
    - base
    - configure
