# This is the top-most playbook, which runs automatically after `vagrant up`

- include: install.yml
- include: configure.yml
- include: wordpress.yml
- include: vagrant.yml
- include: restart-services.yml
