###############
# PROVISIONING
###############

apt:
  # Keys to be added to apt.
  # NOTE: commented out because we do not currently need node on the vm
  # keys:
  #   - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

  # Ppas to be added to apt. Useful ppas (replace trusty with your Ubuntu
  # version codename, if necessary):
  # Git latest:  ppa:git-core/ppa
  # Node.js 5.x: deb https://deb.nodesource.com/setup_5.x trusty main
  ppas:
    - 'ppa:git-core/ppa'
    # NOTE: Node is commented out because we do not currently need node on the vm
    # - "deb https://deb.nodesource.com/setup_5.x trusty main"

  # Any apt packages to install. Apt package versions may be specified like
  # - git=2.1.0
  packages:
    - git
    # NOTE: commented out because we do not currently need node on the vm
    # - nodejs
    - nginx
    - php5-cli
    - php5-fpm
    - php5-mysql
    - php5-curl
    - php5-imagick
    - mysql-server
    - python-mysqldb
