################################################
# Ensure MySQL Databases exist for each WP site
################################################

# Initialize MySQL.

- name: ensure mysql is running
  service: name=mysql state=started enabled=true

# Configure the root MySQL user. (For explanation of these tasks, see the note
# on idempotency on http://docs.ansible.com/ansible/mysql_user_module.html
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - '{{ hostname }}'
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

# Harden MySQL a bit by cleaning up unneeded users and databases.

- name: delete anonymous mysql server user for this hostname
  mysql_user: user="" host={{ hostname }} state=absent

- name: delete anonymous mysql server user for localhost
  mysql_user: user='' state=absent

- name: remove the mysql test database
  mysql_db: db=test state=absent

# Ensure the WP site's database and database user are available

- name: remove the WP database unless explicitly preserving data
  mysql_db: name={{ site.slug }} state=absent
  when: wp_empty_db

- name: ensure database for WP site is present and configured with the proper user
  mysql_db: name={{ site.slug }} state=present
  register: db_state

- name: ensure database users for WP site are present and have all permissions on their corresponding DB
  mysql_user: name={{ site.slug }} password={{ site.slug }} priv={{ site.slug }}.*:ALL,GRANT
  register: db_users
