################################################
# Ensure MySQL Databases exist for each WP site
################################################

# Initialize MySQL.

- name: ensure mysql is running
  service: name=mysql state=started

# Configure the root MySQL user.

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    password: '{{ mysql_root_password }}'
    priv: '*.*:ALL,GRANT'
    host: '{{ item }}'
  with_items:
    - '{{ hostname }}'
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

# Basic MySQL hardening like mysql_secure_installation.

- name: delete anonymous mysql server user for this hostname
  mysql_user: user='' host={{ hostname }} state=absent

- name: delete anonymous mysql server user for localhost
  mysql_user: user='' state=absent

- name: remove the mysql test database
  mysql_db: db=test state=absent

# Ensure databases and database users are available for each WP site.

- name: ensure database users for each site are present
  mysql_user: name={{ item.value.slug }} password={{ item.value.slug }}
  with_dict: sites
  register: db_users

- name: ensure databases for each site are present and configured with the proper user
  mysql_db: name={{ item.value.slug }} login_user={{ item.value.slug }} login_password={{ item.value.slug }} state=present
  with_dict: sites
  register: db_state
